### ISSUE TITLE
Slydes release on apps.fyne.io very out of date (and macOS reports it is "damaged")

### ISSUE THREAD

**Issue by bartgrantham** [andydotxyz/slydes#4]
I watched the fyne.io presentation at GopherCon UK, it was intriguing enough that I wanted to test drive an app or two.  I tried to download Slydes from https://apps.fyne.io/apps/xyz.andy.slydes.html, but the release is pretty old and macOS reports that it is broken:

> “Slydes.app” is damaged and can’t be opened. You should move it to the Trash.

~~Tangentially related is problems with the `fyne` app itself (I can create another issue over there, if it would help):~~

~~If I do `fyne get github.com/andydotxyz/slydes` as suggested on that page, it does appear to clone the repo to a temporary directory in /var/ and then... nothing.  I'm not sure if it built properly or had an error, or if it succeeded and got installed somewhere.  _I don't even know what `fyne get ...` does, exactly_, and I can't find much documentation on the fyne.io site describing what "installation" means.  The online help doesn't give much indication of what to expect besides "Downloads and installs a Fyne application".~~

Edit: `fyne get ...` did install the app into `/Applications` after all, but Spotlight had not indexed it yet.

**Comment by bartgrantham** [comment]
FWIW, I was able to build the latest release of Slydes by manually cloning the repo and `go build .`

**Comment by andydotxyz** [comment]
The build has been updated on our build infra. The "damaged app" is Apple being aggressively anti-hobbyists and it calls the files corrupted just because they have not had a paid-for signature added.
The download page now shows you how to "fix" the issue. This should resolve the issues you saw.
